---
substitutions:
  device_number: "36"
  device_name: i0${device_number}-bathroom-fan

  static_ip: 192.168.128.${device_number}
  log_level: INFO

  device_type: Ruck EM 125L EC 01
  interface: Sonoff MINI R2

  platform: esp8266
  board: esp8285
  arduino_version: recommended

<<: !include templates/common.yaml
<<: !include templates/Sonoff_MINI_R2_fan.yaml
