---

# Log Topic: 'i038/debug'
# Availability: 'i038/status'
# MQTT Switch 'relay': 
#   State Topic: 'i038/switch/relay/state'
#   Command Topic: 'i038/switch/relay/command'
# MQTT Sensor 'temperature':
#   State Topic: 'i038/sensor/temperature/state'
# MQTT Sensor 'humidity':
#   State Topic: 'i038/sensor/humidity/state'
# MQTT Binary Sensor 'button':
#   State Topic: 'i038/binary_sensor/button/state'


substitutions:
  device_number: "38"
  device_name: i0${device_number}-technical-room-pump
  
  static_ip: 192.168.128.${device_number}
  log_level: INFO

  device_type: GRUNDFOS ALPHA1 25-40 180
  interface: Sonoff TH16

  platform: esp8266
  board: esp8285
  arduino_version: recommended

<<: !include templates/Sonoff_TH16_switch.yaml
<<: !include templates/common.yaml



