# Log Topic: 'i038/debug'
# Availability: 'i038/status'
# MQTT Switch 'relay': 
#   State Topic: 'i038/switch/relay/state'
#   Command Topic: 'i038/switch/relay/command'
# MQTT Sensor 'temperature':
#   State Topic: 'i038/sensor/temperature/state'
# MQTT Sensor 'humidity':
#   State Topic: 'i038/sensor/humidity/state'
# MQTT Binary Sensor 'button':
#   State Topic: 'i038/binary_sensor/button/state'


substitutions:
  device_number: "38"
  devicename: "i0${device_number}"
  static_ip: "192.168.128.${device_number}"
  log_level: INFO
  arduino_version: "2.5.2"
  platform: "ESP8266"
  board: "esp8285"

<<: !include templates/common.yaml
<<: !include templates/SonoffTH1601.yaml