# Log Topic: 'i040/debug'
# Availability: 'i040/status'
# MQTT Switch 'relay': 
#   State Topic: 'i040/switch/relay/state'
#   Command Topic: 'i040/switch/relay/command'
# MQTT Binary Sensor 'button':
#   State Topic: 'i040/binary_sensor/button/state'

substitutions:
  device_number: "40"
  devicename: "i0${device_number}"
  static_ip: "192.168.128.${device_number}"
  log_level: INFO
  arduino_version: "2.5.2"
  platform: "ESP8266"
  board: "esp8285"

<<: !include templates/common.yaml
<<: !include templates/SonoffBasic01.yaml