# K2 # direction/K5 # direction of i045/i046 are the opposite from i048
# D1 GPIO5  : K6 # power
# D2 GPIO4  : K3 # direction	
# D3 GPIO0  : K4 # power
# D4 GPIO2 :Connected to onboard LED, HIGH at boot, connected to on-board LED, boot fails if pulled LOW
# D5 GPIO14 : K2 # direction
# D6 GPIO12 : K5 # direction
# D7 GPIO13 : K1 # power

substitutions:
  device_number: "47"
  devicename: "i0${device_number}"
  static_ip: "192.168.128.${device_number}"
  log_level: INFO
  arduino_version: "2.5.2"
  platform: "ESP8266"
  board: "esp12e"

<<: !include templates/common.yaml

switch:
  - platform: gpio
    pin: GPIO2
    id: LED
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO0
    id: K4 # power
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO4
    id: K3 # direction
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO5
    id: K6 # power
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO12
    id: K5 # direction
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO13
    id: K1 # power
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO14
    id: K2 # direction
    restore_mode: ALWAYS_OFF

interval:
  - interval: 1s
    then:
      - switch.toggle: LED

cover:
  - platform: template
    name: rollo1 # living room bay right side
    optimistic: true
    assumed_state: true
    open_action:
      - delay: 250ms
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
      - delay: 250ms
      - switch.turn_on: K1 # power
      - delay: 28s
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
    close_action:
      - delay: 250ms
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_on: K2 # direction
      - delay: 250ms
      - switch.turn_on: K1 # power
      - delay: 25s
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
    stop_action:
      - delay: 250ms
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction

  - platform: template
    name: rollo1-two-third # living room bay right side
    optimistic: true
    assumed_state: true
    open_action:
      - delay: 250ms
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
      - delay: 250ms
      - switch.turn_on: K1 # power
      - delay: 14.0s
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
    close_action:
      - delay: 250ms
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_on: K2 # direction
      - delay: 250ms
      - switch.turn_on: K1 # power
      - delay: 9.3s
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
    stop_action:
      - delay: 250ms
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
     
  - platform: template
    name: rollo2 # living room bay middle
    optimistic: true
    assumed_state: true
    open_action:
      - delay: 250ms
      - switch.turn_off: K4 # power
      - delay: 250ms
      - switch.turn_off: K3 # direction
      - delay: 250ms
      - switch.turn_on: K4 # power
      - delay: 28s
      - switch.turn_off: K4 # power
      - delay: 250ms
      - switch.turn_off: K3 # direction
    close_action:
      - delay: 250ms
      - switch.turn_off: K4 # power
      - delay: 250ms
      - switch.turn_on: K3 # direction
      - delay: 250ms
      - switch.turn_on: K4 # power
      - delay: 28s
      - switch.turn_off: K4 # power
      - delay: 250ms
      - switch.turn_off: K3 # direction
    stop_action:
      - delay: 250ms
      - switch.turn_off: K4 # power
      - delay: 250ms
      - switch.turn_off: K3 # direction

  - platform: template
    name: rollo2-two-third # living room bay middle
    optimistic: true
    assumed_state: true
    open_action:
      - delay: 250ms
      - switch.turn_off: K4 # power
      - delay: 250ms
      - switch.turn_off: K3 # direction
      - delay: 250ms
      - switch.turn_on: K4 # power
      - delay: 13.4s
      - switch.turn_off: K4 # power
      - delay: 250ms
      - switch.turn_off: K3 # direction
    close_action:
      - delay: 250ms
      - switch.turn_off: K4 # power
      - delay: 250ms
      - switch.turn_on: K3 # direction
      - delay: 250ms
      - switch.turn_on: K4 # power
      - delay: 10.4s
      - switch.turn_off: K4 # power
      - delay: 250ms
      - switch.turn_off: K3 # direction
    stop_action:
      - delay: 250ms
      - switch.turn_off: K4 # power
      - delay: 250ms
      - switch.turn_off: K3 # direction

  - platform: template
    name: rollo3 # living room bay left side
    optimistic: true
    assumed_state: true
    open_action:
      - delay: 250ms
      - switch.turn_off: K6 # power
      - delay: 250ms
      - switch.turn_off: K5 # direction
      - delay: 250ms
      - switch.turn_on: K6 # power
      - delay: 28s
      - switch.turn_off: K6 # power
      - delay: 250ms
      - switch.turn_off: K5 # direction
    close_action:
      - delay: 250ms
      - switch.turn_off: K6 # power
      - delay: 250ms
      - switch.turn_on: K5 # direction
      - delay: 250ms
      - switch.turn_on: K6 # power
      - delay: 25s
      - switch.turn_off: K6 # power
      - delay: 250ms
      - switch.turn_off: K5 # direction
    stop_action:
      - delay: 250ms
      - switch.turn_off: K6 # power
      - delay: 250ms
      - switch.turn_off: K5 # direction

  - platform: template
    name: rollo3-two-third # living bay room left side
    optimistic: true
    assumed_state: true
    open_action:
      - delay: 250ms
      - switch.turn_off: K6 # power
      - delay: 250ms
      - switch.turn_off: K5 # direction
      - delay: 250ms
      - switch.turn_on: K6 # power
      - delay: 14.1s
      - switch.turn_off: K6 # power
      - delay: 250ms
      - switch.turn_off: K5 # direction
    close_action:
      - delay: 250ms
      - switch.turn_off: K6 # power
      - delay: 250ms
      - switch.turn_on: K5 # direction
      - delay: 250ms
      - switch.turn_on: K6 # power
      - delay: 9.1s
      - switch.turn_off: K6 # power
      - delay: 250ms
      - switch.turn_off: K5 # direction
    stop_action:
      - delay: 250ms
      - switch.turn_off: K6 # power
      - delay: 250ms
      - switch.turn_off: K5 # direction

