# K2/K5 of i045/i046 are the opposite from i048 (this module)
# D1 GPIO5  : K6
# D2 GPIO4  : K3	
# D3 GPIO0  : K4
# D4 GPIO2 :Connected to onboard LED, HIGH at boot, connected to on-board LED, boot fails if pulled LOW
# D5 GPIO14 : K5
# D6 GPIO12 : K2
# D7 GPIO13 : K1

substitutions:
  device_number: "48"
  devicename: "i0${device_number}"
  static_ip: "192.168.128.${device_number}"
  log_level: INFO
  arduino_version: "2.5.2"
  platform: "ESP8266"
  board: "d1_mini"

<<: !include templates/common.yaml

switch:
  - platform: gpio
    pin: GPIO2
    id: LED
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO0
    id: K4
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO4
    id: K3
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO5
    id: K6
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO12
    id: K2
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO13
    id: K1
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO14
    id: K5
    restore_mode: ALWAYS_OFF

interval:
  - interval: 1s
    then:
      - switch.toggle: LED

cover:
  - platform: template
    name: rollo1 # living room right
    optimistic: true
    assumed_state: true
    open_action:
      - delay: 250ms
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
      - delay: 250ms
      - switch.turn_on: K1 # power
      - delay: 50s
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
    close_action:
      - delay: 250ms
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_on: K2 # direction
      - delay: 250ms
      - switch.turn_on: K1 # power
      - delay: 33s
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
    stop_action:
      - delay: 250ms
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction

  - platform: template
    name: rollo1-two-third # living room right
    optimistic: true
    assumed_state: true
    open_action:
      - delay: 250ms
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
      - delay: 250ms
      - switch.turn_on: K1 # power
      - delay: 20.8s
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
    close_action:
      - delay: 250ms
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_on: K2 # direction
      - delay: 250ms
      - switch.turn_on: K1 # power
      - delay: 12.0s
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
    stop_action:
      - delay: 250ms
      - switch.turn_off: K1 # power
      - delay: 250ms
      - switch.turn_off: K2 # direction
 
  - platform: template
    name: rollo2
    open_action:
      - switch.turn_off: K4
      - delay: 50ms
      - switch.turn_off: K3
      - delay: 50ms
      - switch.turn_on: K4
      - delay: 50s
      - switch.turn_off: K4
    close_action:
      - switch.turn_off: K4
      - delay: 50ms
      - switch.turn_on: K3
      - delay: 50ms
      - switch.turn_on: K4
      - delay: 50s
      - switch.turn_off: K4
      - switch.turn_off: K3
    stop_action:
      - switch.turn_off: K4
      - switch.turn_off: K3
    optimistic: true
    assumed_state: true
 
