---
substitutions:
  device_number: "61"
  device_name: i0${device_number}-office-ac

  static_ip: 192.168.128.${device_number}
  log_level: INFO

  device_type: Mitsubishi SRK 25 ZS
  interface: MHI-AC-Ctrl

  platform: esp8266
  board: d1_mini
  arduino_version: recommended

<<: !include templates/MHI_AC_Ctrl.yaml
