# Based on: 
# https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/blob/master/examples/full.yaml

esphome:
  name: ${device_name}
  platformio_options:
    # Run CPU at 160Mhz to fix mhi_ac_ctrl_core.loop error: -2
    board_build.f_cpu: 160000000L

${platform}:
  board: ${board}
  framework:
    version: ${arduino_version}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  reboot_timeout: 1min

  manual_ip:
    static_ip: ${static_ip}
    gateway: 192.168.128.1
    subnet: 255.255.255.0

logger:
    level: ${log_level}
    baud_rate: 0
    logs:
        # https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/issues/61
        component: ERROR 

ota:
  platform: esphome
  password: !secret ota_password


external_components:
  - source: github://ginkage/MHI-AC-Ctrl-ESPHome@master
    components: [MhiAcCtrl]

api:
  reboot_timeout: 0s
  services:
    - service: set_vertical_vanes
      variables:
        position_value: int # 1-4: static positions, 5: swing, 0: unknown
      then:
        - climate.mhi.set_vertical_vanes:
            position: !lambda "return position_value;"
    - service: set_horizontal_vanes
      variables:
        position_value: int # 1-7: static positions, 8: swing, 0: unknown
      then:
        - climate.mhi.set_horizontal_vanes:
            position: !lambda "return position_value;"
    - service: set_external_room_temperature
      variables:
        temperature_value: float # temperature to set in Celsius
      then:
        - climate.mhi.set_external_room_temperature:
            temperature: !lambda "return temperature_value;"

# Version 4.0

MhiAcCtrl:
  # Only 20 (legacy) or 33 (includes 3D auto and vertical vanes) possible.
  # If you encounter mhi_ac_ctrl_core.loop error: -2 errors, change the frame_size to 20
  frame_size: 33
  initial_vertical_vanes_position: 5
  initial_horizontal_vanes_position: 8
  # Update the following to change the default room temp timeout
  room_temp_timeout: 60

button:
  - platform: restart
    name: "${device_name} Restart"
    entity_category: diagnostic

climate:
  - platform: MhiAcCtrl
    name: ${device_name}
    visual:
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: MhiAcCtrl
    defrost:
      name: "${device_name} Defrost"
    vanes_3d_auto_enabled:
      name: "${device_name} 3D Auto"
  - platform: status
    name: "${device_name} Status"

sensor:
  - platform: uptime
    name: "${device_name} Uptime (s)"
    id: uptime_seconds
    update_interval: 60s
  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s
  - platform: MhiAcCtrl
    outdoor_temperature:
      name: "${device_name} Outdoor temperature"
    return_air_temperature:
      name: "${device_name} Return air temperature"
    outdoor_unit_fan_speed:
      name: "${device_name} Outdoor unit fan speed"
    indoor_unit_fan_speed:
      name: "${device_name} Indoor unit fan speed"
    compressor_frequency:
      name: "${device_name} Compressor frequency"
    indoor_unit_total_run_time:
      name: "${device_name} Indoor unit total run time"
    compressor_total_run_time:
      name: "${device_name} Compressor total run time"
    current_power:
      name: "${device_name} Current power"
    energy_used:
      name: "${device_name} Energy used"
    indoor_unit_thi_r1:
      name: "${device_name} Indoor (U-bend) HE temp 1"
    indoor_unit_thi_r2:
      name: "${device_name} Indoor (capillary) HE temp 2"
    indoor_unit_thi_r3:
      name: "${device_name} Indoor (suction header) HE temp 3"
    outdoor_unit_tho_r1:
      name: "${device_name} Outdoor HE temp"
    outdoor_unit_expansion_valve:
      name: "${device_name} Outdoor unit exp. valve"
    outdoor_unit_discharge_pipe:
      name: "${device_name} Outdoor unit discharge pipe"
    outdoor_unit_discharge_pipe_super_heat:
      name: "${device_name} Outdoor unit discharge pipe super heat"
    protection_state_number:
      name: "${device_name} Compressor protection code"
    error_code:
      name: "${device_name} Error code"
    vanes_pos:
      name: "${device_name} Vanes"
    vanesLR_pos:
      name: "${device_name} Vanes Left/Right"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${device_name} IP"
    ssid:
      name: "${device_name} SSID"
    bssid:
      name: "${device_name} BSSID"
  - platform: MhiAcCtrl
    protection_state:
      name: "${device_name} Compressor protection status"
  - platform: template
    name: "${device_name} Device Type"
    lambda: |-
      return std::string("${device_type}");
    update_interval: 24h # Must be set to something, otherewise value will not show.
    entity_category: diagnostic
    icon: "mdi:information-outline"
  - platform: template
    name: ${device_name} WiFi Channel
    lambda: |-
      return to_string(WiFi.channel());
    update_interval: 60s
    entity_category: diagnostic
    icon: "mdi:wifi"

select:
  - platform: MhiAcCtrl
    vertical_vanes:
      name: "${device_name} Fan Control Up Down"
    horizontal_vanes:
      name: "${device_name} Fan Control Left Right"

switch:
  - platform: MhiAcCtrl
    vanes_3d_auto:
      name: "${device_name} 3D Auto"