# GPIO0	  Button (inverted)
# GPIO12	Relay and Red LED
# GPIO13	Green LED (inverted)
# GPIO1	  UART TX pin (for external sensors)
# GPIO3	  UART RX pin (for external sensors)
# GPIO4	  Optional sensor
# GPIO14	Optional sensor
# GPIO2	  Optional Pin EXP-LOG (TH16 Ver 2.1 2019)


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "relay"
    pin: GPIO12
    id: relay

sensor:
  - platform: dht
    model: AM2302
    pin: GPIO14
    humidity:
      name: "humidity"
    temperature:
      name: "temperature"
    update_interval: 180s

status_led:
  pin:
    number: GPIO13
    inverted: yes
