# GPIO0	  Button (inverted)
# GPIO4	  SW Input
# GPIO12	Relay and Red LED
# GPIO13	Blue LED (inverted)
# GPIO16	Optional sensor

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: button
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle: 
          id: relay

  - platform: gpio
    name: "external_switch"
    pin: GPIO04
    id: external_switch
    on_press:
    - if:
        condition:
          switch.is_on: relay
        then: 
          - switch.turn_off: relay
        else:
          - switch.turn_on: relay
    on_release:
    - if:
        condition:
          switch.is_on: relay
        then: 
          - switch.turn_off: relay
        else:
          - switch.turn_on: relay
switch:
  - platform: gpio
    name: "relay"
    pin: GPIO12
    id: relay
    restore_mode: restore_default_off

status_led:
  pin:
    number: GPIO13
    inverted: true